### ISSUE TITLE
context.Contextが存在せずエラーになる

### ISSUE THREAD

**Issue by elk1997** [takuyaohashi/goincheck#1]
サンプルを実行しましたが、context.Contextの引数がない為エラーが発生します。

`./fetch.go:16: not enough arguments in call to client.GetTicker
	have ()
	want (context.Context)`

バージョン
go version go1.8.3 darwin/amd64

修正方法ありますか？

**Comment by enkaism** [comment]
contextを入れればいいと思いますよー

https://qiita.com/taizo/items/69d3de8622eabe8da6a2

**Comment by takuchalle** [comment]
すいません、サンプルを更新しました。
